### ISSUE TITLE
Improve commit description templates with multiple lines

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#119]
Currently, to get multiple lines in [a commit description](https://github.com/ericcornelissen/svgo-action/blob/develop/docs/configuring-the-commit.md#commit-description) one needs to use `\n` in the template, e.g.:

```yaml
commit:
  description: "This is the first line\nAnd this is the second line"
```

Ideally it would be possible to write this in a more natural way, e.g.:

```yaml
commit:
  description:
    - "This is the first line"
    - "And this is the second line"
```

However, for a blank line this would still require:

```yaml
commit:
  description:
    - "This is the first line"
    - "\n"
    - "And this is the second line"
```

which is admittedly better than:

```yaml
commit:
  description: "This is the first line\n\nAnd this is the second line"
```
