### ISSUE TITLE
Add recommend types in documentation

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#311]
# Documentation

## Description

Update the [README.md > Usage > Install the Action](https://github.com/ericcornelissen/svgo-action#install-the-action) documentation to include (the recommended) [activity types](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request). This could help users reduce the number of times the Action is ran unnecesarily.

For example, for the `pull_request` event the current documentation specifies

> Note: By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword.

However, it is not necessary for this action to be ran when the trigger is `reopened`.

**Comment by ericcornelissen** [comment]
Here are my findings after further investigation:

- `pull_request`: Based on [this list](https://frontside.com/blog/2020-05-26-github-actions-pull_request/) I think it should be `synchronized` and `opened` as these are the only scenarios where there are new commits that were not previously optimized. Maybe, as the default includes `reopened`, it is possible to push to a PR while it is closed without triggering GitHub Actions, so to be sure this should probably actually be equal to the default.
- `push`: I could be helpful to show that you can/one might want to only trigger the workflow on a branch/tag - though that is also the case for Pull Requests and there I am less sure... - so that can be included.
- `schedule`: already OK

Which would look like the following in the README:

```yaml
name: SVGOptimizer
on:
# Disable the following lines if you don't want the Action to run on PRs.
  pull_request:
  - types: [opened, reopened, synchronize]
# Enable the following line if you want the Action to run on regular pushes.
#  push:
#  - branches:
#    - main
# Enable the following lines if you want the Action to run on a schedule.
#  schedule:
#  - cron:  '0 * * * 1'  # See https://crontab.guru/

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: ericcornelissen/svgo-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

Which is starting to make this snippet a little bit messy. Especially given that 1) we actually want to use the default event types for `pull_request` - for which this issue was originally opened - and 2) the addition for push is not clearly beneficial, I'm now less certain this is a good addition... I will leave this open for a bit to allow for feedback.

---

As an aside, if we go ahead with this, the addition of `pull_request_target` in #309 would likely end up having the same types as `pull_request`.
