### ISSUE TITLE
Warning that "ignore" is not an input is invalid

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#326]
# Bug Report

- **SVGO Action version**: v1.2.2 

- **On**: any 

## Description

The [`action.yml` file](https://github.com/ericcornelissen/svgo-action/blob/develop/action.yml) specifies [the `ignore` option](https://github.com/ericcornelissen/svgo-action/blob/develop/docs/options.md#ignore) as "ignore**d**", which causes GitHub Actions to produce a warning if the **correct** key `ignore` is used.

### Actual Behaviour

GitHub Actions produces a warning that the input `ignore` is unexpected.

### Expected Behaviour

GitHub Actions should not produce a warning when the key `ignore` is used.

## Working Example

The bug can be reproduced using the following workflow

```yml
name: SVGOptimizer
on: [push, pull_request]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: ericcornelissen/svgo-action@v1.2.2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        ignore: not/optimized/**/
```
