### ISSUE TITLE
Already optimized SVGs are counted as being optimized

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#362]
# Bug Report

- **SVGO Action version**: [v2.0.0-alpha.3](https://github.com/ericcornelissen/svgo-action/releases/tag/v2.0.0-alpha.3)

- **On**: _any_

## Description

If there is an SVG that is already optimal (i.e. running SVGO on it doesn't change it) the Action still includes the SVG in [its output values](https://github.com/ericcornelissen/svgo-action/blob/d2e69bd448f2c5bac977c8686ca0de596beed629/docs/outputs.md) as being optimized. This is not the case in v1 and shouldn't be the case in v2.

### Actual Behaviour

If there are any optimized SVGs in the context where the SVGO Action is ran these SVGs is counted towards the total of optimized SVGs.

### Expected Behaviour

If there are any optimized SVGs in the context where the SVGO Action is ran these SVGs should _not_ be counted towards the total of optimized SVG.

There may be a new outputted value to count SVGs found that are already optimized, but this is not necessary in order to resolve this bug.

## Working Example

Use the following workflow:

```yml
name: SVGOptimizer
on: [pull_request]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ericcornelissen/svgo-action@next
      id: svgo
    - name: echo optimized count
      run: echo ${{ steps.svgo.outputs.OPTIMIZED_COUNT }}
```

And create a Pull Request adding the following SVG (assuming the default SVGO configuration), make sure there is now final newline, as that will be optimized away.

```svg
<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>
```

Check the output of the Action run output of the last step, it will be 1 (- 1 more than expected, ref. #348).
