### ISSUE TITLE
Misconfiguring dry-run behaviour incorrect

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#409]
# Bug Report

- **SVGO Action version**: [v2.0.2](https://github.com/ericcornelissen/svgo-action/releases/tag/v2.0.2)

- **On**: _any_

## Description

The [inputs documentation](https://github.com/ericcornelissen/svgo-action/blob/484737b010797c8d42e1317adc7f7ffb4d182da8/docs/inputs.md#dry-run) says "If you misconfigure this input the Action assumes you wanted to enable it and set `dry-run` to `true`." This is currently not the case, and if you misconfigure `dry-run` it will **not** be enabled.

This seems to be related to/caused by #400 and/or #402.

### Actual Behaviour

Setting `dry-run` to any invalid value will not enable dry-run.

### Expected Behaviour

Setting `dry-run` to any invalid value enables dry-run.

## Working Example

```yaml
name: Optimize
on: [push]

jobs:
  svgs:
    name: SVGs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ericcornelissen/svgo-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: foobar
```
