### ISSUE TITLE
[Research] Run Action with arbitrary SVGO version

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#437]
# Feature Request

- **SVGO Action version**: [v2.0.5](https://github.com/ericcornelissen/svgo-action/releases/tag/v2.0.5)

- **On**: _any_

## Description

Add the ability to run this Action with any version of SVGO. This solves a couple of problems:

- It is not a problem if there's a new version of SVGO but this Action isn't updated yet. Potentially removing the need to publish an update for a new SVGO version altogether.
- Not every SVGO release requires a corresponding release from the Action (in particular in the case a release for this Action got delayed long enough where SVGO has seen multiple releases).
- User's don't need to stick with an old version of this Action to use a specific SVGO version.

### Example

Run this Action using `ericcornelissen/svgo-action@v2` while pinning the SVGO version to exactly `v2.4.0

## Proposal

Add support for the following:

- [ ] Use an SVGO version installed in a prior step, e.g. using `npm ci` (#462)
- [ ] Use a specified SVGO version, installed by the Action (#463)
- [ ] Use the latest SVGO version, installed by the Action (#465)

**Comment by ericcornelissen** [comment]
Using a project-local SVGO version can be supported using [`sindresorhus/import-cwd`](https://github.com/sindresorhus/import-cwd). An initial proposal in terms of usage for this:

```yaml
 jobs:
   svgs:
     name: SVGs
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Install dependencies
       run: npm ci
     # Or
     - name: Install SVGO
       run: npm install svgo@v2.0.0

     - name: Optimize SVGs
       uses: ericcornelissen/svgo-action@v2
       with:
         repo-token: ${{secrets.GITHUB_TOKEN}}
         svgo-version: project
```

In which case the project-local SVGO version can be obtained as

```js
import importCwd from "import-cwd";

const svgo = importCwd.silent("svgo");
if (svgo === undefined) {
  throw new Error("package-local SVGO not found");
}|
```
