### ISSUE TITLE
Using action on not officially supported event always fails

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#458]
# Bug Report

- **SVGO Action version**: 125e9656bea0c01d70b15865b76d36dbbb9a17c4 (yet to be released as v2.1.1)

- **On**: _any not [officially supported](https://github.com/ericcornelissen/svgo-action/blob/5d1e04615413d8b0af452c23c985cda77e894416/docs/events.md#svgo-action-events) event_

## Description

When the Action is used on a not officially supported event the Action will fail when trying to set output values.

### Actual Behaviour

Action errors.

### Expected Behaviour

Action does not error and (some) outputs are set.

## Working Example

Take for example this workflow:

```yaml
name: SVGOptimizer
on:
  label:
    types: [created, deleted]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ericcornelissen/svgo-action@main
      id: svgo
      with:
        strict: false
    - run: |
        echo ${{steps.svgo.outputs.DID_OPTIMIZE}}
```

This will result in an error where the Action output is as follows

```log
Running SVGO Action in 'label' context
Warning: Event not supported 'label'
Using SVGO major version 2
Error: Failed to set output values
```
