### ISSUE TITLE
Use project's SVGO version

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#462]
# Feature Request

- **SVGO Action version**: [v2.1.1](https://github.com/ericcornelissen/svgo-action/releases/tag/v2.1.1)

- **On**: _any_

## Description

Following the research of #437, add the ability to use an SVGO version installed by the project (e.g. by `npm ci`). This simplifies usage for projects that have their preferred SVGO version defined in a manifest. Additionally it allows users to use a specific version of SVGO plus the latest features of this Action - rather than having to stick with an older version of the Action because the user needs a specific version of SVGO.

### Example

Say I have a job like the one below, than I want this Action to use the SVGO version installed by `npm ci`.

```yaml
 jobs:
   svgs:
     name: SVGs
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Install dependencies
       run: npm ci
     - name: Optimize SVGs
       uses: ericcornelissen/svgo-action@v2
```

## Proposal

Add a special value for [the `svgo-version` input](https://github.com/ericcornelissen/svgo-action/blob/8361b965b69941b8c201ceb871b714beb7e7a9a8/docs/inputs.md#svgo-version) that tells the Action to use the SVGO version found in the project.

The name of this value will be the string `"project"`. If the `svgo-version` input is set to this value it should try to import SVGO from the project. If successful it should use that SVGO version to optimize SVGs. If this fails the Action should stop and error.
