### ISSUE TITLE
Use specific (pinned) SVGO version

### ISSUE THREAD

**Issue by ericcornelissen** [ericcornelissen/svgo-action#463]
# Feature Request

- **SVGO Action version**: [v2.1.1](https://github.com/ericcornelissen/svgo-action/releases/tag/v2.1.1)

- **On**: _any_

## Description

Following the research of #437, add the ability to use a specific SVGO version. This allows users to use a specific SVGO version with the latest features and bugfixes of this Action. On top of that it removes the need to update this Action every time there's a new SVGO release.

### Example

Say I want to use a specific SVGO version, rather than having to downgrade this Action I like in the workflow below, want to use the latest version of this Action.

```yaml
 jobs:
   svgs:
     name: SVGs
     runs-on: ubuntu-latest
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
     - name: Optimize SVGs
       uses: ericcornelissen/svgo-action@v2.0.5
```

## Proposal

Add support to [the `svgo-version` input](https://github.com/ericcornelissen/svgo-action/blob/8361b965b69941b8c201ceb871b714beb7e7a9a8/docs/inputs.md#svgo-version) to accept a specific version number. If this input is set to a specific version it should try to install that version. If the installation fails the Action should fail. If not, the Action should use the specific version.

Version ranges (e.g. `^2.1.0`) are not necessarily in the scope of this issue, but may be supported if it requires little or no additional work.
