### ISSUE TITLE
Could not get GitHub client

### ISSUE THREAD

**Issue by dgibbs64** [ericcornelissen/svgo-action#515]
# Bug Report

- **SVGO Action version**: v2.1.5

- **On**: push

## Description

Action failing with error about "Could not get GitHub client" and "Could not initialize file filters"

### Actual Behaviour

Action failed with teh following

```
| Running SVGO Action in 'push' context
[Optimize SVG Files/SVGs]   💬  ::debug::Initializing GitHub client
[Optimize SVG Files/SVGs]   ❗  ::error::Could not get GitHub client
[Optimize SVG Files/SVGs]   💬  ::debug::Initializing FileSystem to read SVGO config
[Optimize SVG Files/SVGs]   💬  ::debug::Reading the SVGO config file at svgo.config.js
[Optimize SVG Files/SVGs]   💬  ::debug::Parsing SVGO configuration
[Optimize SVG Files/SVGs]   💬  ::debug::Initializing SVGO
[Optimize SVG Files/SVGs]   💬  ::debug::Initializing optimization filters
[Optimize SVG Files/SVGs]   ❗  ::error::Could not initialize file filters
[Optimize SVG Files/SVGs]   💬  ::debug::Initializing FileSystem to read SVGs
[Optimize SVG Files/SVGs]   💬  ::debug::Optimizing SVGs
[Optimize SVG Files/SVGs]   💬  ::debug::Setting outputs
| 
```
yaml
```
name: Optimize SVG Files
on:
  pull_request:

  push:
    branches: [ master ]

jobs:
  svgs:
    name: SVGs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - uses: ericcornelissen/svgo-action@v2.1.5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```
### Expected Behaviour

Action to complete
